name: 'Home Assistant helper: version-push'
description: 'GitHub action helper: version-push'
inputs:
  key:
    required: true
    default: ''
    description: "JSON key to replace version with, e.g. supervisor, homeassistant.default or hassos[] to replace for all properties in hassos."
  key-description:
    required: false
    description: "Human Friendly description of key which is beeing changed for git commit message."
  version:
    required: true
    default: ''
  channel:
    default: 'dev'
runs:
  using: "composite"
  steps: 
    - shell: bash
      id: validate-input
      run: |
        if [[ -z "${{ inputs.key }}" ]];then
          echo "::error::Missing required key 'key' input!"
          exit 1
        elif [[ -z "${{ inputs.version }}" ]];then
          echo "::error::Missing required key 'version' input!"
          exit 1
        fi
        if [[ -z "${{ inputs.key-description }}" ]];then
          echo "key-description=${{ inputs.key }}" >> "$GITHUB_OUTPUT"
        else
          echo "key-description=${{ inputs.key-description }}" >> "$GITHUB_OUTPUT"
        fi
        echo "gitdir=$(mktemp -d)" >> "$GITHUB_OUTPUT"

    - shell: bash
      run: |
        git clone --depth 1 https://github.com/jethubjhaos/version.git "${{ steps.validate-input.outputs.gitdir }}"

    - shell: bash
      run: |
        temp=$(mktemp)
        jq '.${{ inputs.key }} |= "${{ inputs.version }}"' "${{ steps.validate-input.outputs.gitdir }}/${{ inputs.channel }}.json" > "${temp}"
        mv "${temp}" "${{ steps.validate-input.outputs.gitdir }}/${{ inputs.channel }}.json"
        date > ${{ steps.validate-input.outputs.gitdir }}/timestamp

    - shell: bash
      run: |
        cd ${{ steps.validate-input.outputs.gitdir }}
        git commit -am "Bump ${{ steps.validate-input.outputs.key-description }} to ${{ inputs.version }}"
        git push

    - shell: bash
      run: rm -rf "${{ steps.validate-input.outputs.gitdir }}"
